import_zkillboard_watchlist:
  every:
    - "1h"
  queue: low
  custom_job_class: "ImportZkillboardWatchlistJob"
  args:
  description: "Update supers/titans"
update_api_keys_job:
  every:
    - "1h"
  queue: high
  custom_job_class: "UpdateApiKeysJob"
  args:
  description: "Update users api keys"
import_igb_pap_job:
  every:
    - "1h"
  queue: low
  custom_job_class: "ImportIgbPapJob"
  args:
  description: "Update igb pap"
import_igb_fc_pap_job:
  every:
    - "1h"
  queue: low
  custom_job_class: "ImportIgbFcPapJob"
  args:
  description: "Update fc igb pap"
cleanup_imported_pap_job:
  every:
    - "6h"
  queue: low
  custom_job_class: "CleanupImportedPapJob"
  args:
  description: "Update fc igb pap"
close_fleets_job:
  every:
    - "5m"
  queue: medium
  custom_job_class: "CloseFleetsJob"
  args:
  description: "close open fleets"