import_zkillboard_watchlist:
  every:
    - "1h"
  queue: low
  custom_job_class: "ImportZkillboardWatchlistJob"
  args:
  description: "Update supers/titans"
update_api_keys_job:
  every:
    - "1h"
  queue: mediumw
  custom_job_class: "UpdateApiKeysJob"
  args:
  description: "Update users api keys"